def projectName = "frontEnd"
def mails = "christopher.lukombo@outlook.fr;neal.k@hotmail.fr;Angelo.deliessche@gmail.com"

pipeline{
    triggers { pollSCM('H/30 * * * *') }
    options { timeout(time: 1, unit: 'HOURS') }
    agent any
    stages {
        stage("Build") {
            steps {
                script {
                    dir(projectName) {
                        sh("npm install")
                    }
                }
            } 
        }
        stage("Test") {
            steps {
                script {
                    dir(projectName) {
                        sh("npm test")
                    }
                }
            } 
        }
    }
    post {                
        failure {
            emailext(
                body: "Plus d'informations sur : ${env.BUILD_URL}", mimeType: 'text/html',
                replyTo: '', subject: "[${env.JOB_NAME}] Failure - Rapport de build",
                to: "${mails}", recipientProviders: []
            )
        }
        fixed {
            emailext(
                body: "Plus d'informations sur : ${env.BUILD_URL}", mimeType: 'text/html',
                replyTo: '', subject: "[${env.JOB_NAME}] Fixed - Rapport de build",
                to: "${mails}", recipientProviders: []
            )
        }
    }
}