ARG JAR_NAME
ARG JAR_ARGS
ARG JAR_PATH

#on copie le jar depuis jenkins et on le met dans le container
COPY 

# on fait java jar dessus, pas sur de la synthaxe avec docker mais c'est l'idée
CMD ["java ${JAR_ARGS} -jar ${JAR_NAME}"]